<?php

use Drupal\book_bundle\content\ContentConfig;
use Drupal\book_bundle\content\ContentManager;

/**
 * @file
 * Install, update and uninstall functions for the Book Bundle module
 */

/**
 * Implements hook_install()
 */
function book_bundle_install()
{
  $contentManager = \Drupal::classResolver(ContentManager::class);
  $contentManager->createContent();

  $contentConfig = \Drupal::classResolver(ContentConfig::class);
  $contentConfig->setupPathauto();
}
